### ISSUE TITLE
Long response time 

### ISSUE THREAD

**Issue by vzikmund** [logtail/monolog-logtail#16]
Hello, 
we experienced long processing (response) time while sending logs to Logtail few days ago. That issue caused long response time of our API as we are sending data to your API with every request. 

To prevent this to happen again I suggested adding timeouts parameters to cURL instance in the pull request https://github.com/logtail/monolog-logtail/pull/15. 

May I ask you to look into? 

Thank you.

**Comment by curusarn** [comment]
Hi @vzikmund!

Thanks a lot for creating a PR! It looks good to me.
I'm passing it to the team to take another look, merge, and release a new version.

Thanks again for your contribution! 🙏

**Comment by PetrHeinz** [comment]
Hi again @vzikmund, just wanted to tell you that the change is released in [`v2.1.0`](https://github.com/logtail/monolog-logtail/releases/tag/v2.1.0) and [`v3.0.1`](https://github.com/logtail/monolog-logtail/releases/tag/v3.1.0) 🚀 

Thank you for taking the time to create the PR 🙌 We appreciate it!

**Comment by vzikmund** [comment]
Hi @PetrHeinz, 
happy to hear that the feature was released! 

However when I check the Packagist (https://packagist.org/packages/logtail/monolog-logtail) the latest versions are still `v3.0.0` and `v2.0.1`. May I ask you to check it? 🙏

**Comment by PetrHeinz** [comment]
Hi @vzikmund, thank you for reporting that 🙌 

We had auto-update on Packagist enabled, but it didn't register the new releases for an unknown reason... I've forced the sync and both version are now published ✅
